### ISSUE TITLE
After payment: Uncaught Error: Call to a member function getStatus() on null

### ISSUE THREAD

**Issue by xperseguers** [payrexx/prestashop-payrexx-gateway#2]
After proceeding to checkout and payment, Prestashop crashes with a HTTP 500. Looking at the logs shows a null pointer exception in that module:

```
[14-Jan-2023 09:52:34 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to a member function getStatus() on null in /path/to/myshop/home/modules/payrexx/src/Service/PayrexxApiService.php:55
Stack trace:
#0 /path/to/myshop/home/modules/payrexx/controllers/front/validation.php(49): Payrexx\PayrexxPaymentGateway\Service\PayrexxApiService->getTransactionByGateway()
#1 /path/to/myshop/home/classes/controller/Controller.php(306): PayrexxValidationModuleFrontController->initContent()
#2 /path/to/myshop/home/classes/Dispatcher.php(518): ControllerCore->run()
#3 /path/to/myshop/home/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /path/to/myshop/home/modules/payrexx/src/Service/PayrexxApiService.php on line 55
[14-Jan-2023 10:00:30 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to a member function getStatus() on null in /path/to/myshop/home/modules/payrexx/src/Service/PayrexxApiService.php:55
Stack trace:
#0 /path/to/myshop/home/modules/payrexx/controllers/front/validation.php(49): Payrexx\PayrexxPaymentGateway\Service\PayrexxApiService->getTransactionByGateway()
#1 /path/to/myshop/home/classes/controller/Controller.php(306): PayrexxValidationModuleFrontController->initContent()
#2 /path/to/myshop/home/classes/Dispatcher.php(518): ControllerCore->run()
#3 /path/to/myshop/home/index.php(28): DispatcherCore->dispatch()
#4 {main}
  thrown in /path/to/myshop/home/modules/payrexx/src/Service/PayrexxApiService.php on line 55
```

Link to source code where it fails: https://github.com/payrexx/prestashop-payrexx-gateway/blob/master/payrexx/src/Service/PayrexxApiService.php#L55

**Environment:**

- Prestashop v1.7.8.7
- Payrexx gateway module v1.2.2
- PHP 7.4

**Comment by xperseguers** [comment]
Debugging this problem I figured out that the whole logic relies on storing the transaction ID in a cookie. But in my case (and I'd say by default), the cookie as the policy `SameSite=Strict` which is good for login and session stuff but doesn't properly work in the context of Payrexx where there's a redirect at the end of the payment and the cookie, as such, doesn't get properly reloaded.

**Solution::**

- Go to the Prestashop admin
- Open Configure / Advanced Parameters / Administration
- Under General, ensure you have the `Lax` policy for `Cookie SameSite`, instead of `Strict`:

![image](https://user-images.githubusercontent.com/646805/212907645-562aa2d8-b45c-4618-a643-6267d179cf04.png)
